// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://objcklmxfnnsveqhsrok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iamNrbG14Zm5uc3ZlcWhzcm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODYyNTYsImV4cCI6MjA2OTI2MjI1Nn0.d7qKh3jffBDmCZz2pUpRr02SET72PSVnm-N_oUW_DXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});